name: vapourloft
favicon: null
layout_spectrum: 0.804111716337502
typography_spectrum: 0.057892237324267626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3848304997663945
  lightness: 0.7734115065541118
  saturation: 0.6139956701081246
  rhythmicContrast: 0.6116067748516798
purpose: []
